// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class InscripcionModel
{
    [Key]
    [Column("idInscripcion")]
    public int IdInscripcion { get; set; }

    [Column("idEstudiante")]
    public int IdEstudiante { get; set; }
    public string? Estudiante { get; set; }
    public string? Matricula { get; set; }

    [Column("idMateria")]
    public int IdMateria { get; set; }
    public string? Materia { get; set; }

    [Column("idPeriodo")]
    public int IdPeriodo { get; set; }
    public string? Periodo { get; set; }
}