// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class Asistencia
{
    [Key]
    [Column("idAsistencia")]
    public int IdAsistencia { get; set; }

    [Column("idMateria")]
    public int? IdMateria { get; set; }

    [Column("idPeriodo")]
    public int? IdPeriodo { get; set; }

    public DateOnly Fecha { get; set; }

    [InverseProperty("IdAsistenciaNavigation")]
    public virtual ICollection<AsistenciaEstudiante> AsistenciaEstudiante { get; set; } = new List<AsistenciaEstudiante>();

    [ForeignKey("IdMateria")]
    [InverseProperty("Asistencia")]
    public virtual Materia IdMateriaNavigation { get; set; }

    [ForeignKey("IdPeriodo")]
    [InverseProperty("Asistencia")]
    public virtual Periodo IdPeriodoNavigation { get; set; }
}