// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class AsistenciaEstudiante
{
    [Key]
    [Column("idAsistenciaEstudiante")]
    public int IdAsistenciaEstudiante { get; set; }

    [Column("idAsistencia")]
    public int? IdAsistencia { get; set; }

    [Column("idEstudiante")]
    public int? IdEstudiante { get; set; }

    public bool Presente { get; set; }

    [ForeignKey("IdAsistencia")]
    [InverseProperty("AsistenciaEstudiante")]
    public virtual Asistencia IdAsistenciaNavigation { get; set; }

    [ForeignKey("IdEstudiante")]
    [InverseProperty("AsistenciaEstudiante")]
    public virtual Estudiante IdEstudianteNavigation { get; set; }
}