// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class Calificacion
{
    [Key]
    [Column("idCalificacion")]
    public int IdCalificacion { get; set; }

    [Column("idEstudiante")]
    public int? IdEstudiante { get; set; }

    [Column("idMateria")]
    public int? IdMateria { get; set; }

    [Column("idPeriodo")]
    public int? IdPeriodo { get; set; }

    [Column("Calificacion")]
    public int Calificacion1 { get; set; }

    [Column("FRegistro", TypeName = "datetime")]
    public DateTime Fregistro { get; set; }

    [Column("FEvaluacion", TypeName = "datetime")]
    public DateTime Fevaluacion { get; set; }

    [ForeignKey("IdEstudiante")]
    [InverseProperty("Calificacion")]
    public virtual Estudiante IdEstudianteNavigation { get; set; }

    [ForeignKey("IdMateria")]
    [InverseProperty("Calificacion")]
    public virtual Materia IdMateriaNavigation { get; set; }

    [ForeignKey("IdPeriodo")]
    [InverseProperty("Calificacion")]
    public virtual Periodo IdPeriodoNavigation { get; set; }
}