// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class Cuaderno_del_ProfeContext : DbContext
{
    public Cuaderno_del_ProfeContext(DbContextOptions<Cuaderno_del_ProfeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Asistencia> Asistencia { get; set; }

    public virtual DbSet<AsistenciaEstudiante> AsistenciaEstudiante { get; set; }

    public virtual DbSet<Calificacion> Calificacion { get; set; }

    public virtual DbSet<Estudiante> Estudiante { get; set; }

    public virtual DbSet<Inscripcion> Inscripcion { get; set; }

    public virtual DbSet<Materia> Materia { get; set; }

    public virtual DbSet<Periodo> Periodo { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Asistencia>(entity =>
        {
            entity.HasKey(e => e.IdAsistencia).HasName("PK__Asistenc__4E1AB894E64BAB8D");

            entity.HasOne(d => d.IdMateriaNavigation).WithMany(p => p.Asistencia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Asistenci__idMat__66603565");

            entity.HasOne(d => d.IdPeriodoNavigation).WithMany(p => p.Asistencia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Asistenci__idPer__6754599E");
        });

        modelBuilder.Entity<AsistenciaEstudiante>(entity =>
        {
            entity.HasKey(e => e.IdAsistenciaEstudiante).HasName("PK__Asistenc__F47992EFFCDE53A1");

            entity.HasOne(d => d.IdAsistenciaNavigation).WithMany(p => p.AsistenciaEstudiante)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Asistenci__idAsi__6A30C649");

            entity.HasOne(d => d.IdEstudianteNavigation).WithMany(p => p.AsistenciaEstudiante)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Asistenci__idEst__6B24EA82");
        });

        modelBuilder.Entity<Calificacion>(entity =>
        {
            entity.HasKey(e => e.IdCalificacion).HasName("PK__Califica__E056358F0473C0DA");

            entity.HasOne(d => d.IdEstudianteNavigation).WithMany(p => p.Calificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Calificac__idEst__619B8048");

            entity.HasOne(d => d.IdMateriaNavigation).WithMany(p => p.Calificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Calificac__idMat__628FA481");

            entity.HasOne(d => d.IdPeriodoNavigation).WithMany(p => p.Calificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Calificac__idPer__6383C8BA");
        });

        modelBuilder.Entity<Estudiante>(entity =>
        {
            entity.HasKey(e => e.IdEstudiante).HasName("PK__Estudian__AEFFDBC56154C4E3");

            entity.Property(e => e.Sexo).IsFixedLength();
        });

        modelBuilder.Entity<Inscripcion>(entity =>
        {
            entity.HasKey(e => e.IdInscripcion).HasName("PK__Inscripc__3D58AB69F16E8F7B");

            entity.HasOne(d => d.IdEstudianteNavigation).WithMany(p => p.Inscripcion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inscripci__idEst__5CD6CB2B");

            entity.HasOne(d => d.IdMateriaNavigation).WithMany(p => p.Inscripcion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inscripci__idMat__5DCAEF64");

            entity.HasOne(d => d.IdPeriodoNavigation).WithMany(p => p.Inscripcion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inscripci__idPer__5EBF139D");
        });

        modelBuilder.Entity<Materia>(entity =>
        {
            entity.HasKey(e => e.IdMateria).HasName("PK__Materia__4B740AB3A6B9AD04");
        });

        modelBuilder.Entity<Periodo>(entity =>
        {
            entity.HasKey(e => e.IdPeriodo).HasName("PK__Periodo__90A7D3D86E33660C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}