// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

[Index("Matricula", Name = "UQ__Estudian__0FB9FB4F7CA50136", IsUnique = true)]
public partial class Estudiante
{
    [Key]
    [Column("idEstudiante")]
    public int IdEstudiante { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Matricula { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombres { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Apellidos { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Sexo { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Direccion { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string Telefono1 { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string Telefono2 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("FRegistro", TypeName = "datetime")]
    public DateTime Fregistro { get; set; }

    [InverseProperty("IdEstudianteNavigation")]
    public virtual ICollection<AsistenciaEstudiante> AsistenciaEstudiante { get; set; } = new List<AsistenciaEstudiante>();

    [InverseProperty("IdEstudianteNavigation")]
    public virtual ICollection<Calificacion> Calificacion { get; set; } = new List<Calificacion>();

    [InverseProperty("IdEstudianteNavigation")]
    public virtual ICollection<Inscripcion> Inscripcion { get; set; } = new List<Inscripcion>();
}