// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class Inscripcion
{
    [Key]
    [Column("idInscripcion")]
    public int IdInscripcion { get; set; }

    [Column("idEstudiante")]
    public int? IdEstudiante { get; set; }

    [Column("idMateria")]
    public int? IdMateria { get; set; }

    [Column("idPeriodo")]
    public int? IdPeriodo { get; set; }

    [ForeignKey("IdEstudiante")]
    [InverseProperty("Inscripcion")]
    public virtual Estudiante IdEstudianteNavigation { get; set; }

    [ForeignKey("IdMateria")]
    [InverseProperty("Inscripcion")]
    public virtual Materia IdMateriaNavigation { get; set; }

    [ForeignKey("IdPeriodo")]
    [InverseProperty("Inscripcion")]
    public virtual Periodo IdPeriodoNavigation { get; set; }
}