// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class Materia
{
    [Key]
    [Column("idMateria")]
    public int IdMateria { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [InverseProperty("IdMateriaNavigation")]
    public virtual ICollection<Asistencia> Asistencia { get; set; } = new List<Asistencia>();

    [InverseProperty("IdMateriaNavigation")]
    public virtual ICollection<Calificacion> Calificacion { get; set; } = new List<Calificacion>();

    [InverseProperty("IdMateriaNavigation")]
    public virtual ICollection<Inscripcion> Inscripcion { get; set; } = new List<Inscripcion>();
}