// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class Periodo
{
    [Key]
    [Column("idPeriodo")]
    public int IdPeriodo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Column("FInicio")]
    public DateOnly Finicio { get; set; }

    [Column("FFin")]
    public DateOnly Ffin { get; set; }

    [InverseProperty("IdPeriodoNavigation")]
    public virtual ICollection<Asistencia> Asistencia { get; set; } = new List<Asistencia>();

    [InverseProperty("IdPeriodoNavigation")]
    public virtual ICollection<Calificacion> Calificacion { get; set; } = new List<Calificacion>();

    [InverseProperty("IdPeriodoNavigation")]
    public virtual ICollection<Inscripcion> Inscripcion { get; set; } = new List<Inscripcion>();
}