// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

public partial class UsuarioRoles
{
    [Key]
    [Column("idUsuarioRoles")]
    public int IdUsuarioRoles { get; set; }

    public int UsuarioId { get; set; }

    public int RolId { get; set; }

    [ForeignKey("RolId")]
    [InverseProperty("UsuarioRoles")]
    public virtual Roles Rol { get; set; }

    [ForeignKey("UsuarioId")]
    [InverseProperty("UsuarioRoles")]
    public virtual Usuarios Usuario { get; set; }
}