// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cuaderno_del_profe.server.Entities;

[Index("NombreUsuario", Name = "UQ__Usuarios__6B0F5AE010686C6B", IsUnique = true)]
[Index("Email", Name = "UQ__Usuarios__A9D10534E91333D0", IsUnique = true)]
public partial class Usuarios
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string NombreUsuario { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string ContrasenaHash { get; set; }

    [InverseProperty("Usuario")]
    public virtual ICollection<UsuarioRoles> UsuarioRoles { get; set; } = new List<UsuarioRoles>();
}